import type { ChatConversation, ChatMessage } from "./types";

export const MOCK_CONVERSATIONS: ChatConversation[] = [
  {
    id: "c1",
    name: "Maya Okafor",
    username: "maya",
    avatarIdx: 1,
    pinned: true,
    unread: 2,
    lastAt: "now",
    last: "okay but have you SEEN the trailer",
    online: true,
  },
  {
    id: "c2",
    name: "Sunday Coffee ☕",
    username: null,
    avatarIdx: 2,
    group: true,
    members: 4,
    unread: 0,
    lastAt: "14m",
    last: "Jordan: bringing pastries from levain",
  },
  {
    id: "c3",
    name: "Theo Lin",
    username: "theolin",
    avatarIdx: 3,
    unread: 0,
    lastAt: "1h",
    last: "sent you the playlist 🎧",
  },
  {
    id: "c4",
    name: "Priya Raman",
    username: "priya",
    avatarIdx: 4,
    unread: 0,
    lastAt: "3h",
    last: "call you tonight?",
  },
  {
    id: "c5",
    name: "Flat 3B",
    username: null,
    avatarIdx: 5,
    group: true,
    members: 3,
    unread: 0,
    lastAt: "Wed",
    last: "You: I'll grab the detergent",
  },
  {
    id: "c6",
    name: "Noah Perez",
    username: "noah",
    avatarIdx: 0,
    unread: 0,
    lastAt: "Mon",
    last: "safe travels ❤️",
  },
  {
    id: "c7",
    name: "Kira Ahn",
    username: "kira",
    avatarIdx: 2,
    unread: 0,
    lastAt: "Apr 18",
    last: "see you sunday",
  },
];

export const MOCK_THREADS: Record<string, ChatMessage[]> = {
  c1: [
    { id: "m1", from: "them", at: "2:14 PM", text: "hey did you watch it yet" },
    { id: "m2", from: "them", at: "2:14 PM", text: "the new one, the slow-burn sci-fi thing" },
    { id: "m3", from: "me", at: "2:17 PM", text: "half of it! got sleepy at like 11, it's gorgeous though" },
    { id: "m4", from: "me", at: "2:17 PM", text: "that drone shot over the dunes made my jaw drop" },
    {
      id: "m5",
      from: "them",
      at: "2:19 PM",
      text: "okay but have you SEEN the trailer",
      reactions: [{ emoji: "🔥", count: 1 }],
    },
    { id: "m6", from: "them", at: "2:19 PM", text: "because apparently part two is filming in iceland" },
  ],
  c2: [
    { id: "m1", from: "them", who: "Jordan", at: "1:42 PM", text: "who's coming sunday?" },
    { id: "m2", from: "them", who: "Priya", at: "1:45 PM", text: "me!! i'll bring the oat milk this time" },
    { id: "m3", from: "me", at: "1:51 PM", text: "I'm in, usual spot?" },
    { id: "m4", from: "them", who: "Jordan", at: "2:03 PM", text: "bringing pastries from levain" },
  ],
  c3: [
    { id: "m1", from: "them", at: "11:02 AM", text: "made you a playlist. 14 tracks. some are weird. that's the point" },
    { id: "m2", from: "them", at: "11:02 AM", text: "sent you the playlist 🎧" },
    { id: "m3", from: "me", at: "11:10 AM", text: "saving this for tonight's walk. thank you 🙏" },
  ],
  c4: [
    { id: "m1", from: "them", at: "9:20 AM", text: "call you tonight?" },
    { id: "m2", from: "me", at: "9:24 AM", text: "yes please — 8ish?" },
  ],
  c5: [
    { id: "m1", from: "them", who: "Sam", at: "Wed 6:11 PM", text: "we're out of detergent btw" },
    { id: "m2", from: "me", at: "Wed 6:18 PM", text: "I'll grab the detergent" },
  ],
  c6: [
    { id: "m1", from: "them", at: "Mon 8:02 AM", text: "heading to the airport" },
    { id: "m2", from: "me", at: "Mon 8:04 AM", text: "safe travels ❤️" },
  ],
  c7: [{ id: "m1", from: "them", at: "Apr 18", text: "see you sunday" }],
};
